/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HostelGradel;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        new FileHandling().addData("jfldsf", "fsdfs");
        Login loginPage = new Login();
        loginPage.setVisible(true);
        System.out.println(new App().getGreeting());
    }
}
